services:
  waha:
    image: devlikeapro/waha:gows-2026.6.1
    container_name: waha
    restart: always
    ports:
      - "12052:3000"
    environment:
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_DASHBOARD_ENABLED=true
      - WAHA_DASHBOARD_USERNAME=wahaadmin
      - WAHA_DASHBOARD_PASSWORD=${WAHA_PASSWORD}
      - WHATSAPP_SWAGGER_USERNAME=wahaadmin
      - WHATSAPP_SWAGGER_PASSWORD=${WAHA_PASSWORD}