CREATE TABLE IF NOT EXISTS TB_DESTINATIONS(
    ID INT PRIMARY KEY,
    CHAT_ID TEXT NOT NULL
);

INSERT OR IGNORE INTO TB_DESTINATIONS(ID, CHAT_ID) VALUES(1, '554792474906@c.us');

CREATE TABLE IF NOT EXISTS TB_WEATHERVARIABLE(
    ID INT PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL
);

INSERT OR IGNORE INTO TB_WEATHERVARIABLE(ID, DESCRIPTION) VALUES(1, 'TEMPERATURE');
INSERT OR IGNORE INTO TB_WEATHERVARIABLE(ID, DESCRIPTION) VALUES(2, 'HUMIDITY');
INSERT OR IGNORE INTO TB_WEATHERVARIABLE(ID, DESCRIPTION) VALUES(3, 'PRESSURE');
INSERT OR IGNORE INTO TB_WEATHERVARIABLE(ID, DESCRIPTION) VALUES(4, 'WIND_SPEED');
INSERT OR IGNORE INTO TB_WEATHERVARIABLE(ID, DESCRIPTION) VALUES(5, 'PRECIPITATION');

CREATE TABLE IF NOT EXISTS TB_THREASHOLDS(
    ID INT PRIMARY KEY,
    WEATHERVARIABLE INT NOT NULL REFERENCES TB_WEATHERVARIABLE(ID),
    THREASHOLD_VALUE DOUBLE NOT NULL,
    THREASHOLD_TYPE INT NOT NULL
);

-- 1. TEMPERATURE (High): Alarm if MORE THAN 40.0°C (1)
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(1, 1, 40.0, 1);

-- 2. HUMIDITY (High): Alarm if MORE THAN 90% (1)
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(2, 2, 90.0, 1);

-- 3. PRESSURE (Low): Alarm if LESS THAN 980.0 mb (-1)
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(3, 3, 980.0, -1);

-- 4. WIND_SPEED (High): Alarm if MORE THAN 60.0 km/h (1)
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(4, 4, 60.0, 1);

-- 5. PRECIPITATION (High): Alarm if MORE THAN 25.0 mm (1)
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(5, 5, 25.0, 1);

-- 6. TEMPERATURE (Low): Alarm if LESS THAN 5.0°C (-1) -> Frost / Freezing Warning
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(6, 1, 5.0, -1);

-- 7. HUMIDITY (Low): Alarm if LESS THAN 20% (-1) -> High Static / Dehydration / Fire Risk
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(7, 2, 20.0, -1);

-- 8. WIND_SPEED (Low): Alarm if LESS THAN 2.0 km/h (-1) -> Stagnant Air / Pollutant accumulation warning
INSERT OR IGNORE INTO TB_THREASHOLDS(ID, WEATHERVARIABLE, THREASHOLD_VALUE, THREASHOLD_TYPE)
VALUES(8, 4, 2.0, -1);